EMI_CodeAssignment.WebApp/Controllers/ProjectTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMI_CodeAssignment.Business;
using EMI_CodeAssignment.Entities;
using EMI_CodeAssignment.Business.Interfaces;
using EMI_CodeAssignment.Business.Core;

namespace EMI_CodeAssignment.WebApp.Controllers
{
    public class ProjectTasksController : Controller
    {
        private IDataContext db;
        private IRepository<ProjectTask> repo;

        public ProjectTasksController(IDataContext db)
        {
            this.db = db;
            this.repo = RepositoryFactory.GetRepository<ProjectTask>(db);
        }

        // GET: ProjectTasks
        public async Task<ActionResult> Index()
        {
            return View(await repo.GetAsync());
        }

        // GET: ProjectTasks/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            ProjectTask projectTask = await repo.GetAsync(id);
            if (projectTask == null)
            {
                return HttpNotFound();
            }

            return View(projectTask);
        }

        // GET: ProjectTasks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProjectTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "StartDate,EndDate,Description")] ProjectTask projectTask)
        {
            if (ModelState.IsValid)
            {
                repo.Add(projectTask);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(projectTask);
        }

        // GET: ProjectTasks/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            ProjectTask projectTask = await repo.GetAsync(id);
            if (projectTask == null)
            {
                return HttpNotFound();
            }

            return View(projectTask);
        }

        // POST: ProjectTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,StartDate,EndDate,Description,Version")] ProjectTask projectTask)
        {
            if (ModelState.IsValid)
            {
                repo.Update(projectTask);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(projectTask);
        }

        // GET: ProjectTasks/Delete/5
        public async Task<ActionResult> Delete(Guid id)
        {
            ProjectTask projectTask = await repo.GetAsync(id);
            if (projectTask == null)
            {
                return HttpNotFound();
            }

            return View(projectTask);
        }

        // POST: ProjectTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            repo.Delete(id);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

EMI_CodeAssignment.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Project Management App</title>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/calendar.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Project Management App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Resources", "Index", "Resources")</li>
                    <li>@Html.ActionLink("Tasks", "Index", "ProjectTasks")</li>
                    <li>@Html.ActionLink("Allocation", "Tasks", "Allocation")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Project Management App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/underscore.min.js"></script>
    <script src="~/Scripts/calendar.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>